version: '3'

services:
  app:
    container_name: phalcon_app
    build: .
    working_dir: /var/www/html
    volumes:
      - ./html:/var/www/html
    ports:
      - '8080:80'
    expose:
      - '8080'
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    container_name: phalcon_db
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: phalcon_app
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - '3306:3306'
